export const icons = {
  add: './resources/icons/add.svg',
  back: './resources/icons/add.svg',
  forward: './resources/icons/add.svg',
  close: './resources/icons/add.svg',
  refresh: './resources/icons/add.svg',
  search: './resources/icons/add.svg',
  page: './resources/icons/add.svg',
  download: './resources/icons/add.svg',
  history: './resources/icons/add.svg',
  bookmarks: './resources/icons/add.svg',
  settings: './resources/icons/add.svg',
  extensions: './resources/icons/add.svg',
  window: './resources/icons/add.svg',
  more: './resources/icons/add.svg',
  find: './resources/icons/add.svg',
  edit: './resources/icons/add.svg',
  down: './resources/icons/add.svg',
  arrowBack: './resources/icons/add.svg',
  star: './resources/icons/add.svg',
  starFilled: './resources/icons/add.svg',
  fire: './resources/icons/add.svg',
  trash: './resources/icons/add.svg',
  up: './resources/icons/add.svg',
  shield: './resources/icons/add.svg',
  night: './resources/icons/add.svg',
  multrin: './resources/icons/add.svg',
  visible: './resources/icons/add.svg',
  invisible: './resources/icons/add.svg',
  dropDown: './resources/icons/add.svg',
  folder: './resources/icons/add.svg',
  newFolder: './resources/icons/add.svg',
  save: './resources/icons/add.svg',
  weather: {
    day: {
      clear: './resources/icons/add.svg',
      fewClouds: './resources/icons/add.svg',
      rain: './resources/icons/add.svg',
      showers: './resources/icons/add.svg',
      snow: './resources/icons/add.svg',
      storm: './resources/icons/add.svg',
    },
    night: {
      clear: './resources/icons/add.svg',
      fewClouds: './resources/icons/add.svg',
      rain: './resources/icons/add.svg',
      showers: './resources/icons/add.svg',
      snow: './resources/icons/add.svg',
      storm: './resources/icons/add.svg',
    },
  },
};
